id: 9041d02e010042b8a09c9e41924f1fc8
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmpwb5h3mu9.jpg
  credit: tmpd71r1m3e.jpg
